### ISSUE TITLE
UnrealEngine path is not recognized when it is located in another hard disk

### ISSUE THREAD

**Issue by nightrobin** [Erlandys/UE4LinuxLauncher#13]
![Screenshot from 2019-05-02 23-45-49](https://user-images.githubusercontent.com/1894201/57088289-86466c80-6d34-11e9-9f58-1dd96d33e056.png)

**Comment by joaulo** [comment]
I installed on a second HD and it didn't seem to work, but the problem was related to the version (I use 4.22).
I solved it as shown [here](https://github.com/Erlandys/UE4LinuxLauncher/issues/11) and now it works.

![immagine](https://user-images.githubusercontent.com/11321019/57101335-4d50cc80-6d21-11e9-8cb6-9c1afd44bc6b.png)

**Comment by Erlandys** [comment]
Fixed in newest update.
